### ISSUE TITLE
Recaptcha hide

### ISSUE THREAD

**Issue by seda1094** [bhbs/react-google-recaptcha-hook#1]
How is it possible to show the Recaptcha logo only on a specific page(like auth) and hide or make it not work for others?
Thanks!

**Comment by bhbs** [comment]
I implemented methods (`hideGoogleReCaptcha`, `showGoogleReCaptcha`).
Try it out! [new README.md](https://github.com/bhbs/react-google-recaptcha-hook/blob/2d36902741228bb17103cbdb2034546dc77689e3/README.md)

---
I looked for a way to remove it from memory but could not find one. So I implemented a hide option like other libraries. If you want to hide completely and use it, please check [the notes in the official documentation](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed).

Thank you😀

**Comment by seda1094** [comment]
> 

Thanks :)
