### ISSUE TITLE
Error: POST 401 (Unauthorized)

### ISSUE THREAD

**Issue by Bone2510** [bhbs/react-google-recaptcha-hook#60]
Hey Guys, I just wanted to know if this is my fault or if there's someting wrong with the package. On my site I am using the simple example you provided for getting a captcha token. But every time the page reloads or i manually reload the page I get the following error:

recaptcha__de.js:961 
POST https://www.google.com/recaptcha/api2/pat?k=RECAPTCHA_SITE_TOKEN 401 (Unauthorized)

Where RECAPTCHA_SITE_TOKEN is my Site's token (obviously I do not provide it here)

**Comment by bhbs** [comment]
@Bone2510 
Hi, can you try with SITE_TEST_KEY on localhost?
https://github.com/bhbs/react-google-recaptcha-hook/blob/fc49eb63aff6918f4cc0d6d9d31f7766fad5f63b/stories/ReCaptcha.stories.tsx#L6

That's how you'll know if there's a problem with your token or something wrong with the package 😀

**Comment by bhbs** [comment]
If you try entering a some broken token, maybe you'll see other errors.
I think your token is appropriately showing a 401 error for some reason 🤔
